### ISSUE TITLE
torchvision densenet121 无法转成 sparsebit QuantModel

### ISSUE THREAD

**Issue by work-zhangzhe** [megvii-research/Sparsebit#102]
执行如下代码报错：

```python
import torchvision
import torch

from sparsebit.quantization import QuantModel, parse_qconfig


qconfig_path = "./qconfig.yaml"
# BACKEND: virtual
# W:
#   QSCHEME: per-channel-symmetric
#   QUANTIZER: 
#     TYPE: lsq
#     BIT: 4
# A:
#   QSCHEME: per-tensor-affine
#   QUANTIZER:
#     TYPE: lsq
#     BIT: 4
#   QADD:
#     ENABLE_QUANT: true

model = torchvision.models.densenet121(pretrained=True)
qconfig = parse_qconfig(qconfig_path)
model = QuantModel(model, config=qconfig)
inp = torch.randn(2, 3, 224, 224)
out = model(inp)
```

**Comment by PeiqinSun** [comment]
具体报错是?

**Comment by work-zhangzhe** [comment]
具体报错如下：
```text
Traceback (most recent call last):
  File "test.py", line 9, in <module>
    model = QuantModel(model, config=qconfig)
  File "/data/Project/Sparsebit/sparsebit/quantization/quant_model.py", line 36, in __init__
    self._convert2quantmodule()
  File "/data/Project/Sparsebit/sparsebit/quantization/quant_model.py", line 71, in _convert2quantmodule
    new_module = _get_new_qmodule(n.target, org_module)
  File "/data/Project/Sparsebit/sparsebit/quantization/quant_model.py", line 53, in _get_new_qmodule
    new_module = QMODULE_MAP[type(org_module)](org_module)
KeyError: <class 'torch.nn.modules.pooling.AvgPool2d'>
```

**Comment by lz02megv** [comment]
`AvgPool2d` 不在当前已支持的量化算子列表中，正在支持中。

**Comment by PeiqinSun** [comment]
@work-zhangzhe  你是不是直接自己注册一个, 然后交MR就可以?

**Comment by lz02k** [comment]
我交了一版，可供测试和参考 https://github.com/megvii-research/Sparsebit/pull/104

**Comment by mangoguma** [comment]
I also had same error. How to solve it?
