### ISSUE TITLE
error when running generate.py under alpaca-lama

### ISSUE THREAD

**Issue by wesleysanjose** [megvii-research/Sparsebit#139]
it shows following error

Traceback (most recent call last):
  File "/home/missa/dev/Sparsebit/large_language_models/alpaca-qlora/generate.py", line 29, in <module>
    model = PeftQModel.from_pretrained(
  File "/home/missa/miniconda3/envs/sparsebitv6/lib/python3.9/site-packages/peft/peft_model.py", line 135, in from_pretrained
    config = PEFT_TYPE_TO_CONFIG_MAPPING[PeftConfig.from_pretrained(model_id).peft_type].from_pretrained(model_id)
  File "/home/missa/miniconda3/envs/sparsebitv6/lib/python3.9/site-packages/peft/utils/config.py", line 95, in from_pretrained
    if os.path.isfile(os.path.join(pretrained_model_name_or_path, CONFIG_NAME)):
  File "/home/missa/miniconda3/envs/sparsebitv6/lib/python3.9/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType

I see CHECKPOINT_PATH = None in generate.py, is this expected?

**Comment by PeiqinSun** [comment]
yes. and i add a assert in https://github.com/megvii-research/Sparsebit/pull/140
