### ISSUE TITLE
An error about "x_dq = self._forward(x, scale, zero_point) "

### ISSUE THREAD

**Issue by haiduo** [megvii-research/Sparsebit#50]
An error exposing, when I run [cifar10_qat_pact/main.py](https://github.com/megvii-research/Sparsebit/blob/main/examples/cifar10_qat_pact/main.py) . as follows：
```
Traceback (most recent call last):
  File "/root/miniconda3/envs/sb/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/miniconda3/envs/sb/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
 ..........
  File "/root/Sparsebit/examples/cifar10_qat_pact/main.py", line 311, in <module>
    train(
  File "/root/Sparsebit/examples/cifar10_qat_pact/main.py", line 149, in train
    output = model(images)
  File "/root/miniconda3/envs/sb/lib/python3.8/site-packages/torch-1.11.0-py3.8-linux-x86_64.egg/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/Sparsebit/sparsebit/quantization/quant_model.py", line 198, in forward
    return self.model.forward(*args)
  File "<eval_with_key>.129", line 8, in forward
  File "/root/miniconda3/envs/sb/lib/python3.8/site-packages/torch-1.11.0-py3.8-linux-x86_64.egg/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/Sparsebit/sparsebit/quantization/modules/conv.py", line 39, in forward
    x_in = self.input_quantizer(x_in)
  File "/root/miniconda3/envs/sb/lib/python3.8/site-packages/torch-1.11.0-py3.8-linux-x86_64.egg/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/Sparsebit/sparsebit/quantization/quantizers/base.py", line 54, in forward
    x_dq = self._forward(x, scale, zero_point)
TypeError: _forward() takes 2 positional arguments but 4 were given
```
I found that  `def _forward(self, x):` of pact does only accept two parameters, but dorefa does accept four parameters `def _forward(self, x, scale, zero_point):`, and also found that in fact dorefa also only two parameters are required. So, I think there are two solutions:
- either: Change `def _forward(self, x):` of pact to `def _forward(self, x, scale, zero_point):`

- or: Change `def _forward(self, x, scale, zero_point):`  of dorefa to `def _forward(self, x):`, and change [x_dq = self._forward(x, scale, zero_point)](https://github.com/megvii-research/Sparsebit/blob/d8ebc7998034d18b12e126abc66cb9b00848a687/sparsebit/quantization/quantizers/base.py#L54) to:
````
if self.TYPE == "PACT" or self.TYPE == "DoReFa":
     x_dq = self._forward(x)
else:
     x_dq = self._forward(x, scale, zero_point)
````

The error will be solved!

**Comment by PeiqinSun** [comment]
fix in #53
