### ISSUE TITLE
QAT cifar10 example 报错

### ISSUE THREAD

**Issue by work-zhangzhe** [megvii-research/Sparsebit#91]
执行 https://github.com/megvii-research/Sparsebit/blob/main/examples/quantization_aware_training/cifar10/basecase/main.py 报错

- 执行过程
```bash
python3 main.py qconfig_lsq.yaml --epochs=0
```

- 报错
```text
Traceback (most recent call last):
  File "main.py", line 428, in <module>
    main()
  File "main.py", line 219, in main
    qmodel.export_onnx(
  File "/data/Project/Sparsebit/sparsebit/quantization/quant_model.py", line 254, in export_onnx
    self.add_extra_info_to_onnx(name)
  File "/data/Project/Sparsebit/sparsebit/quantization/quant_model.py", line 298, in add_extra_info_to_onnx
    input_dequant = nodes[tensor_inputs[onnx_op.input[0]][0]]
KeyError: 'conv1.weight_quantizer.scale'
```

**Comment by PeiqinSun** [comment]
fixed in https://github.com/megvii-research/Sparsebit/pull/92
